# Generated by Django 4.0.4 on 2022-04-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApacheLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes_sent', models.IntegerField(blank=True, null=True, verbose_name='Bytes Sent')),
                ('remote_host', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remote Host')),
                ('remote_logname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remote Log Name')),
                ('remote_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remote User')),
                ('request_line', models.CharField(blank=True, max_length=100, null=True, verbose_name='Request Line')),
                ('final_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Final Status')),
                ('request_time', models.DateTimeField(blank=True, null=True, verbose_name='Request Time')),
            ],
        ),
    ]
