# Generated by Django 4.0.4 on 2022-04-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_log_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Access Log Path')),
            ],
        ),
    ]
