# Generated by Django 4.0.4 on 2022-04-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_parser', '0005_alter_configuration_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='file_path',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/', verbose_name='File Path'),
        ),
    ]
