# Generated by Django 4.0.4 on 2022-04-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_parser', '0008_configuration_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='apachelogs',
            name='referer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referer'),
        ),
        migrations.AddField(
            model_name='apachelogs',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User Agent'),
        ),
    ]
